### ISSUE TITLE
Problem Installing on Debian Stretch

### ISSUE THREAD

**Issue by chriscroome** [asamuzaK/withExEditorHost#13]
I'm not sure if I'm doing something wrong here but I have tried this:

```bash
wget https://github.com/asamuzaK/withExEditorHost/archive/v2.0.0-b.18.tar.gz
tar -zxvf v2.0.0-b.18.tar.gz
mv withExEditorHost-2.0.0-b.18/ withExEditorHost
cd withExEditorHost/
npm install
node setup.js
/home/firefox/withExEditorHost/setup.js:48
  const createEditorConfig = async () => {
                                   ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

This is with the Debian Stretch version of node:

```
apt show -a nodejs
Package: nodejs
Version: 6.11.3-1nodesource1
Priority: optional
Section: web
Maintainer: Chris Lea <chl@nodesource.com>
Installed-Size: 44.4 MB
Provides: nodejs-dev, nodejs-legacy, npm
Depends: libc6 (>= 2.4), libgcc1 (>= 1:3.4), libstdc++6 (>= 4.1.1), python-minimal, ca-certificates
Conflicts: nodejs-dev, nodejs-legacy, npm
Replaces: nodejs-dev (<= 0.8.22), nodejs-legacy, npm (<= 1.2.14)
Homepage: https://nodejs.org
Download-Size: 9,881 kB
APT-Manual-Installed: yes
APT-Sources: https://deb.nodesource.com/node_6.x jessie/main amd64 Packages
Description: Node.js event-based server-side javascript engine
 Node.js is similar in design to and influenced by systems like
 Ruby's Event Machine or Python's Twisted.
 .
 It takes the event model a bit further - it presents the event
 loop as a language construct instead of as a library.
 .
 Node.js is bundled with several useful libraries to handle server tasks :
 System, Events, Standard I/O, Modules, Timers, Child Processes, POSIX,
 HTTP, Multipart Parsing, TCP, DNS, Assert, Path, URL, Query Strings.

Package: nodejs
Version: 4.8.2~dfsg-1
Priority: extra
Section: web
Maintainer: Debian Javascript Maintainers <pkg-javascript-devel@lists.alioth.debian.org>
Installed-Size: 14.3 MB
Provides: nodejs-abi-46
Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.4), libicu57 (>= 57.1-1~), libssl1.0.2 (>= 1.0.2d), libstdc++6 (>= 5.2), libuv1 (>= 1.6.1), zlib1g (>= 1:1.1.4)
Recommends: ca-certificates
Homepage: http://nodejs.org/
Tag: devel::interpreter, devel::lang:ecmascript, devel::runtime, devel::web,
 implemented-in::c++, implemented-in::ecmascript,
 interface::commandline, interface::shell, protocol::dns,
 protocol::http, protocol::tcp, role::program, scope::application,
 works-with-format::json
Download-Size: 3,440 kB
APT-Sources: https://mirrorservice.org/sites/ftp.debian.org/debian stretch/main amd64 Packages
Description: evented I/O for V8 javascript
 Node.js is a platform built on Chrome's JavaScript runtime for easily
 building fast, scalable network applications. Node.js uses an
 event-driven, non-blocking I/O model that makes it lightweight and
 efficient, perfect for data-intensive real-time applications that run
 across distributed devices.
 .
 Node.js is bundled with several useful libraries to handle server
 tasks:
 .
 System, Events, Standard I/O, Modules, Timers, Child Processes, POSIX,
 HTTP, Multipart Parsing, TCP, DNS, Assert, Path, URL, Query Strings.

```

**Comment by asamuzaK** [comment]
Host v2.x is for node.js v8.
Update node.js and try again.

or

Download host v1.x which supports node.js v6.
https://github.com/asamuzaK/withExEditorHost/releases/tag/v1.4.2

**Comment by chriscroome** [comment]
Thanks, that did the trick :-)

**Comment by chriscroome** [comment]
I have now updated to node.js v8:

```bash
wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
echo "deb https://deb.nodesource.com/node_8.x jessie main" > /etc/apt/sources.list.d/nodesource.list
apt install node
```

Just leaving this here in case it helps anyone in the future (this is a simple version of [this bash script](https://deb.nodesource.com/setup_8.x)).
