### ISSUE TITLE
index setup command

### ISSUE THREAD

**Issue by OrionRandD** [asamuzaK/withExEditorHost#50]
when I issue:

index setup

I get "command not found"
So, that I cannot install the host :(

**Comment by OrionRandD** [comment]
Also with 
node index setup I get this:

node index setup

[1] firefox
[2] chrome
[3] chromium
[4] vivaldi
[0] CANCEL

Select a browser. [1...4 / 0]: 1
(node:3130) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'mkdir' of undefined
    at createDirectory (/home/vagner/Downloads/withExEditorHost/node_modules/web-ext-native-msg/modules/file-util.js:206:21)
    at Setup._createConfigDir (/home/vagner/Downloads/withExEditorHost/node_modules/web-ext-native-msg/modules/setup.js:404:29)
    at Setup._createFiles (/home/vagner/Downloads/withExEditorHost/node_modules/web-ext-native-msg/modules/setup.js:416:34)
    at Setup._handleBrowserConfigDir (/home/vagner/Downloads/withExEditorHost/node_modules/web-ext-native-msg/modules/setup.js:452:19)
    at Setup._handleBrowserInput (/home/vagner/Downloads/withExEditorHost/node_modules/web-ext-native-msg/modules/setup.js:473:19)
    at Setup.run (/home/vagner/Downloads/withExEditorHost/node_modules/web-ext-native-msg/modules/setup.js:500:19)
    at Command.runSetup (/home/vagner/Downloads/withExEditorHost/index.js:654:16)
    at Command.listener (/home/vagner/Downloads/withExEditorHost/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
(node:3130) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:3130) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by asamuzaK** [comment]
* Download the host from the [latest release](https://github.com/asamuzaK/withExEditorHost/releases/).
* Or, if you want to setup host from the source code of current master branch, update your Node.js to latest LTS and try again.

Master branch is in progress for the next major release.
I'm planning to drop support for Node v8.x in the next major release (Node v8.x is not active LTS anymore).

> (node:3130) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'mkdir' of undefined
> at createDirectory (/home/vagner/Downloads/withExEditorHost/node_modules/web-ext-native-msg/modules/file-util.js:206:21)

The error is because of the API (Promise based mkdir function) which is implemented in Node 10.0.0.

**Comment by OrionRandD** [comment]
Thx a lot.
I will try to install the last version
:)

**Comment by asamuzaK** [comment]
Good to hear.
I'll close this.
