### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by derobert** [asamuzaK/withExEditorHost#70]
Trying to run "setup" from git latest gives an error:

```
$ node index setup
/home/anthony/src/withExEditorHost/modules/setup.js:152
    setup.supportedBrowsers = setup.supportedBrowsers.filter(item =>
                                                      ^

TypeError: Cannot read property 'filter' of undefined
    at Command.runSetup (/home/anthony/src/withExEditorHost/modules/setup.js:152:55)
    at Command.listener (/home/anthony/src/withExEditorHost/node_modules/commander/index.js:291:8)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (/home/anthony/src/withExEditorHost/node_modules/commander/index.js:672:12)
    at Command.parse (/home/anthony/src/withExEditorHost/node_modules/commander/index.js:459:21)
    at Object.<anonymous> (/home/anthony/src/withExEditorHost/index.js:31:11)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

Latest code:
```
$ git rev-parse HEAD
9b23180bf56a177e1869edc4fbc0e6dff21334d2
```

Am running latest Node LTS:

```
$ node --version
v12.13.0
```

**Comment by asamuzaK** [comment]
Are you running host from source?
If so, try `npm run setup`, not `node index setup`.
Ref [asamuzaK/withExEditorHost: Native messaging host for withExEditor](https://github.com/asamuzaK/withExEditorHost#host-setup-from-source-code)

**Comment by asamuzaK** [comment]
By the way, the host is provided as an npm module, so unless you want to debug or fork from source, I recommend getting the host from npm.

**Comment by derobert** [comment]
Thank you, that worked. I read the wrong section of the README.
